config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  root 'hello#index'
  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
  resources :users, only: [:show]
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :tweet_tag_relations, dependent: :destroy
    has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :tweet_tag_relations, dependent: :destroy
    has_many :tags, through: :tweet_tag_relations, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    scope :latest, -> {order(created_at: :desc)}
    scope :old, -> {order(created_at: :asc)}
    scope :high, -> {order(price: :desc)}
    scope :low, -> {order(price: :asc)}
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters

      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!

    def index
        @tweets = Tweet.all


        if params[:latest]
          @tweets = Tweet.latest
        elsif params[:old]
          @tweets = Tweet.old
        elsif params[:like]
          @tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
        elsif params[:high]
          @tweets = Tweet.high
        elsif params[:low]
          @tweets = Tweet.low
        elsif params[:tag_ids].present?
          @tags = Tag.where(id: params[:tag_ids])
          @tweets = Tweet.joins(:tags).where(tags: { id: @tags.pluck(:id) }).distinct
        else
          @tweets = Tweet.all
        end
      end

    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @tweet = Tweet.find(params[:id])
      end
      def edit
        @tweet = Tweet.find(params[:id])
      end
      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end
      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end


      private
      def tweet_params
        params.require(:tweet).permit(:image,:name,:detail,:price,:link,tag_ids: [])
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<div class="background-container">
    <div class="toumei">

        <div class="otomo"><h1>Otomo</h1><p>～ご飯のお供紹介サイト～</p></div>
        <div class="center3">
        <p>ご飯をおいしく食べるために必須であるご飯のお供の紹介サイトです</p>
        <p>ご飯のお供の写真や価格や販売サイトへのURLといった情報も掲載</p>
        <p>豊富なタグで食べたいお供を見つけ出そう</p>
        <p>おいしかったお供はいいね機能で友達におすすめしよう</p>
        </div>

            <div class="image-container">
            <%#= image_tag 'image1.jpg', alt: '画像1' %>
            <%#= image_tag 'image2.jpg', alt: '画像2' %>
            <%#= image_tag 'image3.jpg', alt: '画像3' %>
            <%#= image_tag 'image4.jpg', alt: '画像4' %>
            <%#= image_tag 'image5.jpg', alt: '画像5' %>
            <%#= image_tag 'image6.jpg', alt: '画像6' %>
            </div>

    </div>

</div>

app/views/hello/link.html.erb

このページ使わないのでメモ帳にしてます

<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', tweets_path %>

<%= link_to "ログイン", tweets_path %>
<%= link_to "新規サインアップ", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otomo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d4cd2a33d0.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+One&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Mochiy Pop One', sans-serif;
        }
    </style>
  </head>

  <body>
    <header>
      <p><%= link_to '', hello_index_path, class: "fa-solid fa-house"%></p>
      <div class="header-list">
        <ul>
          <% if user_signed_in? %>
          <li><%= link_to "投稿一覧", tweets_path %></li>
          <li><%= link_to "新規投稿",new_tweet_path %></li>
          <li><%= link_to "マイページ",user_path(current_user.id) %></li>
          <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'button-link' %></li>
          <% else %>
          <li><%= link_to "ログイン", tweets_path %></li>
          <% end %>
        </ul>
      </div>
    </header>
    <main>
    <div class="toumei">
      <%= yield %>
    </div>
    </main>
  </body>
</html>

app/views/tweets/edit.html.erb
<div class="center">
<div class="edit">
<h1>Edit</h1>
</div>
</div>

<div class="blank1">

    <%= form_for @tweet do |f| %>
      <div class="field">
        <%= f.label :写真　　　　　 %>
        <%= f.file_field :image %>
      </div>

  <div class="field">
    <%= f.label :商品名　　　　 %>
    <%= f.text_field :name, :size => 100 %>
  </div>

  <div class="field">
    <%= f.label :商品の概要　　 %>
    <%= f.text_field :detail, :size => 100 %>
  </div>

  <div class="field">
    <%= f.label :値段（税込）　 %>
    <%= f.number_field :price,  min: 100, max: 15000 %>
  </div>

  <div class="field">
    <%= f.label :ホームページ　 %>
    <%= f.text_field :link, :size => 100 %>
  </div>


<div class='field'>
  <div class='tags'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        
            <%= tag.label class: 'form-check-label' do %>
                <%= tag.check_box class: 'form-check-input' %>
                <%= tag.text %>
            <% end %>
        
    <% end %>
  </div>
</div>

<div class="center2">
<%= f.submit "編集する", class: 'search-button' %>
</div>
<% end %>


</div>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="center">
<h1 class="posts">Posts</h1>


<p><%= link_to '新しい順', tweets_path(latest: "true") %>
<%= link_to '古い順', tweets_path(old: "true") %>
<%= link_to 'いいね順', tweets_path(like: "true") %>
<%= link_to '価格が高い順', tweets_path(high: "true") %>
<%= link_to '価格が低い順', tweets_path(low: "true") %></p>

<div class="tag-labe">
<p><%#= form_tag({controller:"tweets",action:"index"}, method: :get) do %></p>
    <%# Tag.all.each do |t| %>
        <%#= check_box :tag_ids, t.name %><%#= t.name %>
    <%# end %>
    </div>
    <p><%#= submit_tag '検索', class: 'search-button'%></p>
<%# end %>
</div>

<%= form_tag({ controller: "tweets", action: "index" }, method: :get) do %>
  <div class="tag-search">
    <div class="tags">
        <% Tag.all.each do |t| %>
        <div class="tag-item">
            <%= check_box_tag 'tag_ids[]', t.id, false, id: "tag_#{t.id}", class: 'tag-checkbox' %>
            <%= label_tag "tag_#{t.id}", t.name, class: 'tag-label' %>
        </div>
        <% end %>
        <%= submit_tag '検索', class: 'search-button' %>
    </div>
  </div>
<% end %>


<div class="post-list">
    <% @tweets.each do |t| %>
        <div class="post">

            <% if t.image.attached? %>
                <%= image_tag t.image, style: 'width: auto; height: 250px;'%>
            <% end %>

            <p><%= t.name %></p>
            <p>税込￥<%= t.price %></p>

            <div class="post-tag">
            <% t.tags.each do |tag| %>
                #<%= tag.name %>
            <% end %>
            </div>


            <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete, class: "like-button" do %>
                        <i class="fa-solid fa-heart fa-1x"></i><%= t.likes.count %>
                    <% end %>
                <% else %>
                    <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post, class: "like-button" do %>
                        <i class="fa-regular fa-heart fa-1x"></i><%= t.likes.count %>
                    <% end %>
                <% end %>
            <% else %>
                <i class="fa-solid fa-star"><%= t.likes.count %>
            <% end %>

                <%= link_to "詳細", tweet_path(t.id) %>
            <% if user_signed_in? && current_user.id == t.user_id %>
                <%= link_to "編集", edit_tweet_path(t.id) %>
            <% end %>
        </div>
    <% end %>
</div>



app/views/tweets/new.html.erb
<div class="center">
<div class="new">
<h1>New Post</h1>
</div>
</div>

<div class="blank1">


    <%= form_for @tweet do |f| %>
      <div class="field">
        <%= f.label :写真　　　　　 %>
        <%= f.file_field :image %>
      </div>

      <div class="field">
        <%= f.label :商品名　　　　 %>
        <%= f.text_field :name, :size => 100 %>
      </div>

      <div class="field">
        <%= f.label :商品の概要　　 %>
        <%= f.text_field :detail, :size => 100 %>
      </div>

      <div class="field">
        <%= f.label :値段（税込）　 %>
        <%= f.number_field :price,  min: 100, max: 15000 %>
      </div>

      <div class="field">
        <%= f.label :ホームページ　 %>
        <%= f.text_field :link, :size => 100 %>
      </div>

      <div class='field'>
        <div class='tags'>
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                
                    <%= tag.label class: 'form-check-label' do %>
                        <%= tag.check_box class: 'form-check-input' %>
                        <%= tag.text %>
                    <% end %>
                
            <% end %>
        </div>
      </div>

      <div class="center2">
      <%= f.submit "投稿する", class: 'search-button'  %>
      </div>
    <% end %>



</div>

app/views/tweets/show.html.erb

<div class="center">

<div class="detail">
<h1>Details</h1>
</div>



  <div class="detail-image">
  <% if @tweet.image.attached? %>
    <%= image_tag @tweet.image, style: 'width: auto; height: 500px;'%>
  <% end %>
  </div>

  <div class="detail-box">
      <span class="box-title">基本情報</span>
      <p>投稿者名：<%= @tweet.user.name %></p>
      <p>商品名：<%= @tweet.name %></p>
      <p>値段：<%= @tweet.price %>円</p>
      <p>購入サイト：<a href="<%= @tweet.link %>"><%= @tweet.link %></a></p>
      <p>いいねしたユーザー：<% @tweet.liked_users.each do |user| %>
                              <%= user.name %>
                            <% end %></p>
  </div>

  <div class="detail-box">
      <span class="box-title">詳細</span>
      <p><%= @tweet.detail %></p>
      <div class="post-tag">
        <p><% @tweet.tags.each do |tag| %>
            #<%= tag.name %>
           <% end %></p>
        <p><% if user_signed_in? %>
            <% if current_user.already_liked?(@tweet) %>
              <%= button_to tweet_like_path(@tweet), method: :delete, class: "like-button" do %>
                <i class="fa-solid fa-heart fa-1x"></i><%= @tweet.likes.count %>
              <% end %>
            <% else %>
              <%= button_to tweet_likes_path(@tweet), method: :post, class: "like-button" do %>
                <i class="fa-regular fa-heart fa-1x"></i><%= @tweet.likes.count %>
              <% end %>
            <% end %>
          <% else %>
            <i class="fa-solid fa-star"></i><%= @tweet.likes.count %>
          <% end %></p>
      </div>
  </div>


</div>
<%= link_to "投稿一覧に戻る", tweets_path %>
<% if user_signed_in? && current_user.id == @tweet.user_id %>
  <%= link_to "編集", edit_tweet_path(@tweet.id) %>
  <%= button_to "削除", tweet_path(@tweet.id), method: :delete %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb

<div class="center">
<div class="mypage">
<h1>My Page</h1>
</div>

<div class="field">
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>ひとこと : <%= @user.profile %></p>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>
</div>


<div class="edituser">
<h1>My Posts</h1>
</div>

<div class="post-list">
  <% @user.tweets.each do |t| %>
  <div class="post">
    <% if t.image.attached? %>
      <%= image_tag t.image, style: 'width: auto; height: 250px;'%>
    <% end %>
    <p><%= t.name %></P>
    <%= link_to "詳細", tweet_path(t.id) %>
  </div>
  <% end %>
</div>



<div class="posts">
<h1>My Likes</h1>
</div>
<div class="post-list">
  <% @user.liked_tweets.each do |t| %>
  <div class="post">
    <% if t.image.attached? %>
      <%= image_tag t.image, style: 'width: auto; height: 250px;'%>
    <% end %>
    <p><%= t.name %></p>
    <%= link_to "詳細", tweet_path(t.id) %>
  </div>
  <% end %>
</div>

</div>
<%= link_to "投稿一覧に戻る", tweets_path %>